### ISSUE TITLE
Sandstorm: Prepopulated element not held in sandstorm

### ISSUE THREAD

**Issue by RevanthRS** [Mercury1089/2019-scouting-app#88] opened 2019-03-08 23:25 UTC
Expected result: if an element was selected as Prepopulated, that element is held actively in sandstorm.

Actual Result: if an element was selected as Prepopulated, it is not held in sandstorm.

**Comment by sreffler** [comment] 2019-03-09 01:10
Duplicate of #79, reopening 79

**Closed as completed by sreffler** 2019-03-09 01:10 UTC
Labels: duplicate
