### ISSUE TITLE
Lift partners I highlighted when the wrong option is selected

### ISSUE THREAD

**Issue by RevanthRS** [Mercury1089/2019-scouting-app#92] opened 2019-03-09 00:54 UTC
"Did they lift any partners" should be highlighted only when yes is selected for "did they end on hab" but instead it is only highlighted when no is selected

**Comment by sreffler** [comment] 2019-03-09 05:28
Ok as is, duplicate of #91 and works as intended (you can help partners without being on the platform yourself)

**Closed as completed by sreffler** 2019-03-09 05:28 UTC
Labels: invalid, bug (low priority), Climbing
